version: '3'
services:
  app:
    container_name: "club-manager"
    build:
      dockerfile: docker/Dockerfile
      context: ../
      args:
        # STAGE: dev
        STAGE: ${APP_ENV}
    volumes:
      - ./:/app
    ports:
      - "${PORT}:8080"
    tty: true
    stdin_open: true
