@startuml
title 承認・却下ワークフロー

participant 創部申請者
participant 承認者

創部申請者 -> SlackApp: 任意のチャンネルからスラッシュコマンドを使って創部申請
SlackApp -> 承認者: 承認権限をもつユーザーが参加している承認専用チャンネルに創部申請が届いたことを知らせる
承認者 -> SlackApp: 承認専用チャンネルに届いた創部申請情報に埋め込まれている承認画面ボタンをクリック
SlackApp -> 承認者: 承認用モーダルを表示

alt 承認する場合
    承認者 -> SlackApp: 承認用モーダルに表示された承認ボタンを押す
    SlackApp -> 創部申請者: 創部申請者と設立発起人をまとめてユーザーグループに追加
    alt 部活チャンネル作成済で、フォームに部活チャンネルIDを入力している場合
        SlackApp -> スプレッドシート: 部活動名と同じレコードにチャンネルIDを追加
        SlackApp -> 創部申請者: 部活チャンネルにてユーザーグループを使って承認通知
    end
    alt Kibelaの部活動/非公認フォルダーに記事作成済で、フォームに記事URLを入力している場合
        SlackApp -> Kibela: 記事を部活動/公認フォルダーに移動
        創部申請者 <- SlackApp: 部活チャンネルにてユーザーグループを使ってKibela記事を公認フォルダーに移動したことを通知
    end
    SlackApp -> 創部申請者: 創部通知専用チャンネルである#notificationで部員全員に対しユーザーグループを使って承認通知
else 却下する場合
    承認者 -> SlackApp: 承認用モーダルに表示された却下ボタンを押す
    SlackApp -> 創部申請者: DMに却下された理由を送信
end
@enduml