@startuml
title 承認・却下ワークフロー

participant 創部申請者
participant 承認者

創部申請者 -> SlackApp: 任意のチャンネルからスラッシュコマンドを使って創部申請
alt 入力された部活チャンネルIDがスプレッドシート上に存在する場合
    SlackApp ->> スプレッドシート: 該当する部活レコードの部活名セルを入力された部活名に更新
else 入力された部活チャンネルIDがスプレッドシート上に存在しない場合
    SlackApp ->> スプレッドシート: 部活マスタタブに行追加
end
スプレッドシート -->> SlackApp: 完了
SlackApp -> 承認者: 承認権限をもつユーザーが参加している承認専用チャンネルに創部申請が届いたことを知らせる
承認者 -> SlackApp: 承認専用チャンネルに届いた創部申請情報に埋め込まれている承認画面ボタンをクリック
SlackApp -> 承認者: 承認用モーダルを表示
alt 承認する場合
    承認者 -> SlackApp: 承認用モーダルに表示された承認ボタンを押す
    SlackApp ->> スプレッドシート: 該当する部活レコードの公認セルにチェックを入れる
    スプレッドシート -->> SlackApp: 完了
    SlackApp -> 創部申請者: チャンネル(notification/部活/管理部)にて承認したことを通知
    opt Kibelaの部活動/非公認フォルダーに記事作成済で、フォームに記事URLを入力している場合
        SlackApp ->> Kibela: 記事を部活動/公認フォルダーに移動
        Kibela -->> SlackApp: 完了
        SlackApp -> 創部申請者:  チャンネル(notification/部活/管理部)にてKibela記事を公認フォルダーに移動したことを通知
    end
else 却下する場合
    承認者 -> SlackApp: 承認用モーダル内で却下理由を入力し、却下ボタンを押す
    SlackApp -> 創部申請者: チャンネル(notification/部活/管理部)にて申請が却下されたこと&却下理由を通知
end
@enduml
