@startuml
title 創部フロー
創部申請者 -> SlackApp: ワークフロー製のモーダルから創部申請
SlackApp ->> スプレッドシート: 部活マスタタブに行追加
SlackApp ->> 管理部: 決定権を持つ人に、確認メッセージを送る

alt 承認された場合
    管理部 -->> SlackApp: 承認
    SlackApp ->> スプレッドシート: 該当する部活の公認カラムにチェックを入れる
    SlackApp ->> スプレッドシート: シートに部活動名と同じタブを追加
    SlackApp ->> kibela: 部活動/非公認フォルダーに記事が書いてあったら公認フォルダに移動
    SlackApp -> 創部申請者: 創部申請者と設立発起人をまとめてユーザーグループに追加
    SlackApp -> 創部申請者: 設立されたというメッセージを各チャンネル(notification/各部活/管理部)に送信
else 非承認の場合
    管理部 -->> SlackApp: 却下
    SlackApp -> 創部申請者: 却下されたというメッセージを各チャンネル(notification/各部活/管理部)に送信
end

@enduml