@startuml
title 創部フロー
創部申請者 -> SlackBot: モーダルから創部申請
SlackBot --> スプレッドシート: 部活マスタタブに行追加
SlackBot -> 管理部: 決定権を持つ人に、確認メッセージを送る

alt 承認された場合
    管理部 -> SlackBot: 承認
    SlackBot --> スプレッドシート: 該当する部活の公認カラムにチェックを入れる
    SlackBot --> スプレッドシート: シートに部活動名と同じタブを追加
    SlackBot --> kibela: 記事が書いてあったら非公認から公認フォルダに移動
    SlackBot --> 創部申請者: 創部申請者と設立発起人をまとめてユーザーグループに追加
    SlackBot -> 創部申請者: グループに設立されたというメッセージを送信
else 非承認の場合
    管理部 -> SlackBot: 非承認
    SlackBot -> 創部申請者: 却下されたというメッセージを送信
end

@enduml