name: Lint

on:
  push:
    branches:
      - main
      - "release*"
      - "feat*"
  pull_request:
    branches:
      - main
      - "release*"
      - "feat*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [11.15.0]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
      - run: npm run install:all
      - run: npm run lint
